<?php
// This file generated by Propel 1.6.7 convert-conf target
// from XML runtime conf file D:\Projects\localhost\data_dikdas\app\config\runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'data_dikdas' => 
    array (
      'adapter' => 'pgsql',
      'connection' => 
      array (
		'dsn' => 'pgsql:dbname='.DATABASENAME.';host='.DATABASEHOST.';port=5433;user='.DATABASEUSER.';password='.DATABASEPASSWORD,
        'persistent' => true,
      ),
    ),
    'default' => 'data_dikdas',
  ),
  'generator_version' => '1.6.7',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-data_dikdas-conf.php');
return $conf;
