<?php
// This file generated by Propel 1.6.7 convert-conf target
// from XML runtime conf file D:\Projects\localhost\data_dikdas\app\config\runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'data_dikdas' => 
    array (
      'adapter' => 'pgsql',
      'connection' => 
      array (
        'dsn' => 'pgsql:dbname=pendataan;host=localhost;user=postgres;password=ddikdas5',
        'persistent' => true,
        'settings' => 
        array (
          'charset' => 
          array (
            'value' => 'utf8',
          ),
          'queries' => 
          array (
            'query' => 'set search_path to public, ref, nilai, blob',
          ),
        ),
      ),
    ),
    'default' => 'data_dikdas',
  ),
  'generator_version' => '1.6.7',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-data_dikdas-conf.php');
return $conf;